import { ArrowLeftIcon } from '@heroicons/react/outline'
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import CommentModal from '../../components/CommentModal'
import Comments from '../../components/Comments'
import Post from '../../components/Post'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import { db } from '../../firebase'


export default function PostPage({ newsResults, randomUserResults }) {

    const [post, setPost] = useState();
    const [comments, setComments] = useState();

    const postId = useSelector((state) => state.Comment.postIds);
    const open = useSelector((state) => state.Comment.open);

    const router = useRouter();
    const { id } = router.query;


    // get post data

    useEffect(() => {
        onSnapshot(doc(db, "posts", id), (snapshot) => {
            setPost(snapshot)
        })
    }, [id, db])


    //get comments of post 
    useEffect(() => {
        onSnapshot(
            query(
                collection(db, "posts", id, "comments"),
                orderBy("timestamp", "desc")
            ),
            (snapshot) => setComments(snapshot.docs)
        );
    }, [db, id]);

    return (
        <div >
            <Head>
                <title>Twitter Clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='flex min-h-screen mx-auto'>

                {/* Sidbar */}
                <Sidebar />

                {/* Feed */}
                <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
                    <div className="flex items-center space-x-2  py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
                        <div className="hoverEffect" onClick={() => router.push("/")}>
                            <ArrowLeftIcon className="h-5 " />
                        </div>
                        <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
                            Tweet
                        </h2>
                    </div>
                    <Post id={id} post={post} />


                    <div>
                        {
                            comments.map((comment) => (
                                <Comments
                                    key={comment.id}
                                    commentId={comment.id}
                                    originalPostId={id}
                                    comment={comment.data()}
                                />
                            ))
                        }
                    </div>

                </div>


                {/* Widgets */}
                <Widgets newsResults={newsResults.articles} randomUserResults={randomUserResults.results} />

                {/* Modal */}

                <CommentModal />

            </main>

        </div>
    )
}

export const getServerSideProps = async () => {

    const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json")
        .then((res) => res.json());

    // hwo to follo section
    const randomUserResults = await fetch("https://randomuser.me/api/?results=50&inc=name,login,picture")
        .then((res) => res.json());

    return {
        props: {
            newsResults,
            randomUserResults
        }
    }
}