import Head from 'next/head'
import { useSelector } from 'react-redux'
import CommentModal from '../components/CommentModal'
import Feed from '../components/Feed'
import LogoutModal from '../components/LogoutModal'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'


export default function Home({ newsResults, randomUserResults }) {


  return (
    <div >
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen mx-auto '>

        {/* Sidbar */}
        <Sidebar />

        {/* Feed */}
        <Feed />

        {/* Widgets */}
        <Widgets newsResults={newsResults.articles} randomUserResults={randomUserResults.results} />

        {/* Modal */}

        <CommentModal />

        <LogoutModal />

      </main>

    </div>
  )
}

export const getServerSideProps = async () => {

  const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json")
    .then((res) => res.json());

  // hwo to follo section
  const randomUserResults = await fetch("https://randomuser.me/api/?results=50&inc=name,login,picture")
    .then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUserResults
    }
  }
}